### ISSUE TITLE
Enquiry about the package's features

### ISSUE THREAD

**Issue by teddychao** [martin3141/spant#10]
Hi,

I am Teddy from UoB Cancer Science. I just found the package and feel attracted by its modern design and features. However, I am a little confused about how overlapping it is with TARQUIN. I was using TARQUIN throughout my PhD project (through macOS terminal) and it works unbelievable. I am not sure if I will be encouraged to migrate to spant or continue to stay in TARQUIN? I am developing a wavelet-based package but unfortunately on MATLAB.. If spent has everything that TARQUIN can do, I hope to build a R version to make them work together if possible.

Thanks.

Best wishes
Teddy

**Comment by martin3141** [comment]
Hi Teddy,

So spant is a general package for MRS analysis. The focus is on giving the user multiple options for various parts of the analysis pipeline. eg more than one method for coil combination, drift correction, fitting algorithm.

With TARQUIN the workflow is more restricted, which is good if it works for you, but otherwise limited. The main issue with TARQUIN is that it is written in c++ and therefore very difficult to support for all three platforms (for me at least). I don't own a Mac right now, so if there is a bug in the version you are using - it won't get fixed unless you are willing to compile it yourself. Same goes for Windows - but for different reasons. spant is *much* easier to support on different platforms.

It's hard for me to say what you should use in the future, at it's quite application specific. If TARQUIN does everything you need then by all means stick with it. If you're analysing MRSI and have problems with baseline, then spant + ABFit is going to work better. If you want to develop a method for detecting movement corrupted shots spant is going to be better suited. If you want to compare a new residual water suppression method, spant is going to work better. If you want to have a custom and reproducible analysis pipeline, including machine learning, stats and plots - spant is going to be best (https://github.com/martin3141/neuro_metabolic_phenotyping). spant it being more regularly updated - which you might find annoying as scripts you write might need to be updated once in a while.

You can of course have the best of both worlds and use TARQUIN from within spant ;)

Something else to consider is FID-A (https://github.com/CIC-methods/FID-A) which is MATLAB based - and might suit you better if you want to integrate with your existing code.

Hope that helps,

Martin
